
    create table cart (
        id integer generated by default as identity,
        quantity integer,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table favorites (
        id integer generated by default as identity,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table product (
        price float(53),
        quantity integer,
        rating integer,
        shell_id integer,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        category varchar(255),
        code varchar(255) not null unique,
        description varchar(255),
        image varchar(255),
        internal_reference varchar(255),
        inventory_status varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        firstname varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists cart 
       add constraint fk_cart_product 
       foreign key (product_id) 
       references product;

    alter table if exists cart 
       add constraint fk_cart_users 
       foreign key (user_id) 
       references users;

    alter table if exists favorites 
       add constraint fk_favorites_product 
       foreign key (product_id) 
       references product;

    alter table if exists favorites 
       add constraint fk_favorites_users 
       foreign key (user_id) 
       references users;

    create table cart (
        id integer generated by default as identity,
        quantity integer,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table favorites (
        id integer generated by default as identity,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table product (
        price float(53),
        quantity integer,
        rating integer,
        shell_id integer,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        category varchar(255),
        code varchar(255) not null unique,
        description varchar(255),
        image varchar(255),
        internal_reference varchar(255),
        inventory_status varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        firstname varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists cart 
       add constraint FK3d704slv66tw6x5hmbm6p2x3u 
       foreign key (product_id) 
       references product;

    alter table if exists cart 
       add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 
       foreign key (user_id) 
       references users;

    alter table if exists favorites 
       add constraint FKs08qf83fj01k3epnxh9n71v1s 
       foreign key (product_id) 
       references product;

    alter table if exists favorites 
       add constraint FKk7du8b8ewipawnnpg76d55fus 
       foreign key (user_id) 
       references users;

    create table cart (
        id integer generated by default as identity,
        quantity integer,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table favorites (
        id integer generated by default as identity,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table product (
        price float(53),
        quantity integer,
        rating integer,
        shell_id integer,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        category varchar(255),
        code varchar(255) not null unique,
        description varchar(255),
        image varchar(255),
        internal_reference varchar(255),
        inventory_status varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        firstname varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists cart 
       add constraint FK3d704slv66tw6x5hmbm6p2x3u 
       foreign key (product_id) 
       references product;

    alter table if exists cart 
       add constraint FKg5uhi8vpsuy0lgloxk2h4w5o6 
       foreign key (user_id) 
       references users;

    alter table if exists favorites 
       add constraint FKs08qf83fj01k3epnxh9n71v1s 
       foreign key (product_id) 
       references product;

    alter table if exists favorites 
       add constraint FKk7du8b8ewipawnnpg76d55fus 
       foreign key (user_id) 
       references users;
