openapi: 3.0.3
info:
  title: User Account API
  version: 1.0.0
paths:
  /account:
    post:
      summary: Create a new user account
      operationId: createUserAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccountDTO'
      responses:
        '201':
          description: User account created
  /token:
    post:
      summary: Authenticate user
      operationId: connectUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDTO'
      responses:
        '200':
          description: Authentication successful
components:
  schemas:
    UserAccountDTO:
      type: object
      properties:
        username:
          type: string
        firstname:
          type: string
        email:
          type: string
        password:
          type: string
    UserLoginDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserDTO:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        firstname:
          type: string
        email:
          type: string
        password:
          type: string
        cart:
          type: array
          items:
            $ref: '#/openapi_product.yaml/components/schemas/ProductSummaryDTO'
        favorites:
          type: array
          items:
            $ref: '#/openapi_product.yaml/components/schemas/ProductSummaryDTO'